apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: iftg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iftg
    app.kubernetes.io/part-of: byoc-app-epnh
  name: iftg
spec:
  rules:
  - host: iftg-byoc-odox-tenant.apps.8cba7189c4d1e98fac44.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: iftg
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
